### ISSUE TITLE
Why "Always use markdown for README"?

### ISSUE THREAD

**Issue by nedbat** [amontalenti/elements-of-python-style#6]
GitHub and Bitbucket will both render ReStructured text natively.  Why use .rst for docstrings and docs, and then have one piece left over as Markdown?  PyPI doesn't yet render Markdown, so Markdown will leave you looking like a foreigner on PyPI, while .rst will look good everywhere.

I think better advice is, "Use ReStructured Text everywhere."

**Comment by amontalenti** [comment]
@nedbat I think you're right. This document started as an internal document for my company, and we had long ago decided to make our README's markdown simply because not every project at the company is a pure Python project (e.g. reST is foreign to JavaScript folks). I will update the recommendation to suggest .rst which I think is a better style choice for Python projects more generally.

**Comment by amontalenti** [comment]
Addressed this in f6656af5, closing. Thanks @nedbat!

**Comment by pydanny** [comment]
:smile: 

I like Markdown, I really do. But when writing code for Python, I stick with RST.
